# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rflocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='cellid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Network Cell Id'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='devid',
            field=models.CharField(default=0, max_length=200, verbose_name='Device Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='source',
            field=models.CharField(default='HMM', max_length=100, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='ups',
            field=models.IntegerField(default=0, verbose_name='Device Uptime'),
            preserve_default=False,
        ),
    ]
